[build]
command = "curl https://sh.rustup.rs -sSf | sh -s -- -y && source $HOME/.cargo/env && cargo install trunk && trunk build --release"
publish = "dist"

[[redirects]]
from = "/api/*"
to = "http://100.115.254.48:5000/:splat"
status = 200
force = true
